DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS quote;
DROP TABLE IF EXISTS vote;

CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE                         NOT NULL DEFAULT now(),
    updated   TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    user_name TEXT,
    email     TEXT,
    password  TEXT

);

CREATE TABLE IF NOT EXISTS quote
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created       TIMESTAMP WITHOUT TIME ZONE                         NOT NULL DEFAULT now(),
    updated       TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    quote_content TEXT,
    vote_amount   BIGINT                                                       DEFAULT 0,
    user_id       BIGINT references users (id)
);

CREATE TABLE IF NOT EXISTS vote
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created    TIMESTAMP WITHOUT TIME ZONE                         NOT NULL DEFAULT now(),
    updated    TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    vote_count BIGINT,
    quote_id   BIGINT references quote (id),
    user_id    BIGINT references users (id)
);
